default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *default
  database: fs_cources_dev

test:
  <<: *default
  database: fs_cources_test

production:
  <<: *default

staging:
  <<: *default
